#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://causality.pl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Causality
email      : jakub.kopyto@causality.pl #this is also the email contact forms will go to
description: "Causality - machine learning researchers, software developers and more. We are able to help you to tackle your data with Artificial Intelligence. Read more and contact us to find out more"
author     : Causality
keywords   : "causality,machine,learning,software,development"
og:
  image: /android-chrome-512x512.png
logo:     #optional, defaults to site title
  path: assets/img/brand/Causality-logos_monster.png
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  blog:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:project/:title

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xlekdbar"

plugins:
  - jekyll-remote-theme
